# Generated by Django 4.0.4 on 2022-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='slide title')),
                ('referral_link', models.URLField(verbose_name='referral link')),
                ('referral_link_text', models.CharField(max_length=30, verbose_name='referral link text')),
                ('desktop_image', models.ImageField(upload_to='slider', verbose_name='slide image (desktop)')),
                ('mobile_image', models.ImageField(upload_to='slider', verbose_name='slide image (mobile)')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='slide image (intro)')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('contents', models.ManyToManyField(related_name='collections', to='content.content', verbose_name='contents')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
    ]
