# Generated by Django 4.0.4 on 2022-07-13 16:01

import apps.subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.subscription.models.discount_code_generator, max_length=5, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'discount code',
                'verbose_name_plural': 'discount codes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_time', models.PositiveSmallIntegerField(help_text='Plan time (month)', verbose_name='plan time')),
                ('price', models.DecimalField(decimal_places=0, help_text='Enter price in toman.', max_digits=6, verbose_name='price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, help_text='Enter discounted price in toman.', max_digits=6, null=True, verbose_name='discounted price')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
            },
        ),
    ]
